name: dart_hydrologis_utils
description: Common dart utilities lib for our projects.
version: 0.5.4+2
repository: https://github.com/moovida/dart_hydrologis_utils
issue_tracker: https://github.com/moovida/dart_hydrologis_utils/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # BSD
  # timezone: ^0.5.7
  # BSD
  intl: '>=0.16.1 <=0.17.0'
  # Apache 2.0
  image: '>=2.1.17 <3.0.0-nullsafety.0'
  path: ^1.7.0

  # MIT
  xml: '>=4.3.0 <=5.0.2'



dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
