name: dart_hydrologis_utils
description: Common dart utilities lib for our projects.
version: 0.1.0
homepage: https://www.hydrologis.com
repository: https://github.com/moovida/dart_hydrologis_utils
issue_tracker: https://github.com/moovida/dart_hydrologis_utils/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # APACHE 2.0
  chunked_stream: ^1.1.0
  # MIT
  logger: ^0.8.3
  # BSD
  timezone: ^0.5.7
  # BSD
  characters: ^0.5.0
  # BSD
  intl: ^0.16.1
  # Apache 2.0
  image: ^2.1.12

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
